name: 'otel-github-grafana-exporter'
description: 'Exports traces from Github Actions Workflows to Grafana Cloud'
author: 'Nick Keers'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  grafanaEndpoint:
    description: 'Your Grafana OTLP endpoint'
    required: true
  grafanaInstanceID:
    description: 'Your Grafana Cloud Instance ID'
    required: true
  grafanaAccessPolicyToken:
    description: 'Your Grafana Access Policy token'
    required: true
  otelServiceName:
    description: 'OTEL service name'
    required: false
  githubToken:
    description: 'Github auth token'
    required: true

runs:
  using: node20
  main: dist/index.js
