name: Trace Tester

on: [push]

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Dummy step 1
        run: echo "Dummy step 1 completed."
      - name: Dummy step 2
        run: sleep 5 && echo "Dummy step 2 completed."

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Dummy step 1
        run: sleep 3 && echo "Dummy step 1 completed."
      - name: Dummy step 2
        run: echo "Dummy step 2 completed."